# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pytube
import os
import sys
import messagebox as msg

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(691, 558)
        MainWindow.setMaximumSize(QtCore.QSize(691, 558))
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        MainWindow.setAcceptDrops(False)
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(True)
        self.label_3.setMinimumSize(QtCore.QSize(300, 150))
        self.label_3.setMaximumSize(QtCore.QSize(700, 300))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("youtube_logo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(34)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(75, 75, 75);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.txt_link = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_link.setObjectName("txt_link")
        self.horizontalLayout.addWidget(self.txt_link)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.txt_nome_arquivo = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_nome_arquivo.setObjectName("txt_nome_arquivo")
        self.horizontalLayout_2.addWidget(self.txt_nome_arquivo)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radio_mp3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_mp3.setChecked(True)
        self.radio_mp3.setObjectName("radio_mp3")
        self.verticalLayout.addWidget(self.radio_mp3)
        self.radio_mp4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_mp4.setObjectName("radio_mp4")
        self.verticalLayout.addWidget(self.radio_mp4)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_download = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_download.setFont(font)
        self.btn_download.setObjectName("btn_download")
        self.verticalLayout_3.addWidget(self.btn_download)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txt_link, self.txt_nome_arquivo)
        MainWindow.setTabOrder(self.txt_nome_arquivo, self.radio_mp3)
        MainWindow.setTabOrder(self.radio_mp3, self.radio_mp4)
        MainWindow.setTabOrder(self.radio_mp4, self.btn_download)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Youtube Download"))
        self.label_4.setText(_translate("MainWindow", "Download"))
        self.label.setText(_translate("MainWindow", "Link"))
        self.label_2.setText(_translate("MainWindow", "Titulo"))
        self.radio_mp3.setText(_translate("MainWindow", "mp3"))
        self.radio_mp4.setText(_translate("MainWindow", "mp4"))
        self.btn_download.setText(_translate("MainWindow", "Download"))

        # Botao Download #
        self.btn_download.clicked.connect(self.download)

    def download(self):
        url = self.txt_link.text()
        nome_arquivo = self.txt_nome_arquivo.text()

        if len(url) <= 0:
            msg.show_critical_messagebox("Insira um link do youtube para baixar!")
            self.txt_link.setFocus()
            return
        elif len(nome_arquivo) <= 0:
            msg.show_critical_messagebox("Digite o nome do arquivo!")
            self.txt_nome_arquivo.setFocus()
            return

        try:
            yt = pytube.YouTube(url)
            if self.radio_mp4.isChecked():
                video = yt.streams.get_highest_resolution()
                video.download(filename=nome_arquivo)

            elif self.radio_mp3.isChecked():
                audio = yt.streams.filter(only_audio=True).first()
                out_file = audio.download(filename=nome_arquivo)
                base, ext = os.path.splitext(out_file)
                new_file = base + '.mp3'
                os.rename(out_file, new_file)

            else:
                msg.show_critical_messagebox("Selecione o tipo de arquivo [mp3 - mp4]!")
                self.radio_mp3.setFocus()
                return

            msg.show_info_messagebox("Download concluído com sucesso!")
            self.txt_link.setText('')
            self.txt_nome_arquivo.setText('')
            self.txt_link.setFocus()

        except Exception as err:
            msg.show_critical_messagebox(err)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
